apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-persisent-volume-claim
spec:
  volumeName: airflow-dags-persisent-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
