apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-persisent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: airflow-dags-persisent-volume-claim
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/k8/airflow-data/dags"
