apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: app-db
  replicas: 1
  template:
    metadata:
      labels:
        app: app-db
    spec:
      containers:
        - name: app-db
          image: postgres:13
          ports:
            - containerPort: 5432
              name: "postgres"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-data-storage
          env:
            - name: POSTGRES_DB
              value: football-db
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
      volumes:
        - name: postgres-data-storage
          persistentVolumeClaim:
            claimName: db-storage-persisent-volume-claim
