apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-storage-persisent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: db-storage-persisent-volume-claim
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/k8/data/"
