apiVersion: v1
kind: Service
metadata:
  name: premier-league-rest-api-service
spec:
  selector:
    app: premier-league-rest-api-go
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
